name: Update Commit Hash

on:
  push:
    branches:
      - main

jobs:
  create-version-file:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Get the latest commit hash
        id: get_commit_hash
        run: echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Create hash file
        run: |
          echo -e "VERSION = \"${{ env.COMMIT_HASH }}\"\n" > module_name/commit_hash.py

      - name: Commit and push hash file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f module_name/commit_hash.py  # 忽略 .gitignore 中的规则强制添加
          git commit -m "[Action] auto update commit hash file"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
